### ISSUE TITLE
redefinate the built-in acosh function

### ISSUE THREAD

**Issue by pleasurefish** [jolivain/glslsandbox-player#7]
RightAngledHexagons meets function redefinition: (19:0) : error : Redefining function:  'acosh' is disallowed. The “acosh” is a built-in function name. According to GLES 3.x Spec, this behavior is not allowed.
https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf

**Comment by jolivain** [comment]
Hi @pleasurefish,

I agree that redefining a builtin is forbidden in GLSL ES.

Indeed, the spec at
https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf
says in section: 4.2.3. Redeclaring Names

> Names of built-in functions cannot be redeclared as functions. Therefore overloading or redefining built-in functions is an error.

However, the same spec also says, in section: 3.3. Version Declaration

> Version 1.00 of the language does not require shaders to include this directive, and shaders that do not include a #version directive will be treated as targeting version 1.00.

glslsandbox-player is indeed an OpenGL ES 2.0 application. It presents
itself as such, at:
https://github.com/jolivain/glslsandbox-player/blob/v2023.04.05/src/egl_helper.c#L540

Shader code does not include the #version directive either. They should be interpreted as GLSL ES 1.00, even by an OpenGL ES 3.2 implementation.

Looking at GLSL ES 1.00 spec:
https://registry.khronos.org/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf
There is no "acosh()" builtin present in that version.  It was indeed introduced in GLSL ES 3.00.

OpenGL ES 3.2 spec says in section: 1.5. Compatibility

> The OpenGL ES 3.2 API is designed to work with GLSL ES v1.00, GLSL ES 3.00, GLSL ES 3.10 and GLSL ES 3.20. In general a shader written for versions prior to OpenGL ES 3.2 should work without modification in OpenGL ES 3.2.

Shader listed in glslsandbox-player are validated with glslangValidator. See:
https://github.com/jolivain/glslsandbox-player/blob/v2023.04.05/README.md#validating-builtin-shaders

You can test the shader in GLSL ES 1.00, with the following commands:

    ./scripts/dl-shader 75209.0 > glsles100.frag
    glslangValidator glsles100.frag && echo OK || echo FAIL

Which will output:

    OK

Shader compilation passes, in GLSL ES 1.00. It can also be tested in GLSL ES 3.20, by adding the appropriate `#version`:

    ( echo '#version 320 es' ; cat glsles100.frag ) > glsles320.frag
    glslangValidator glsles320.frag && echo OK || echo FAIL

With GLSL ES 3.20, it now fails to the reason you mention:

    glsles320.frag
    ERROR: 0:19: 'redefinition of built-in function' : not supported with this profile: es
    ERROR: 0:19: 'mediump' : overloaded functions must have the same parameter precision qualifiers for argument 1
    ERROR: 0:19: 'acosh' : function name is redeclaration of existing name 
    ERROR: 0:19: 'acosh' : function already has a body 
    ERROR: 0:20: '' : compilation terminated 
    ERROR: 5 compilation errors.  No code generated.

    FAIL

For info, I tested with Glslang Version: 11:12.1.0, ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 12.1.0.

Therefore, I believe this is a GPU driver bug on your side (which incorrectly applies the GLSL ES 3.20 interpretation instead of 1.00). You can share your GPU driver identification, if you like, from the output of "glslsandbox-player -v", or by using the script in:
https://github.com/jolivain/glslsandbox-player/blob/v2023.04.05/scripts/bug-report-info.sh

Best regards,

Julien.

**Comment by pleasurefish** [comment]
thanks Julien. i will check it again with Vivante guys.
